# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
#cache: packages
warnings_are_errors: false
r_packages:
  - covr
  - rsconnect
  - devtools
  - memoise
  - parsedate
  - plyr
  - rappdirs
  - rcmdcheck
  - rematch
  - rhub
  - rversions
  - RSelenium
  - dplyr
  - rlang
  - plyr

after_success:
  - Rscript -e 'covr::codecov()'

# For shinyapps.io deployment
deploy:
  - provider: script
    script: 
      - R -f deploy.R
    on:
      branch: master