# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
r_packages:
  - covr
  - rsconnect
  - gfpopgui

after_success:
  - Rscript -e 'covr::codecov()'

# Added for shinyapps.io deployment
dist: xenial
sudo: false
latex: false

deploy:
  provider: script
  script: 
    - R -f deploy.R
  on:
    branch: troubleshoot_deploy