# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
r_packages:
  - covr
  - rsconnect
  - devtools
  - memoise
  - parsedate
  - plyr
  - rappdirs
  - rcmdcheck
  - rematch
  - rhub
  - rversions
  - RSelenium
  - dplyr
  - rlang
  - plyr

after_success:
  - Rscript -e 'covr::codecov()'

script:
- nohup R --slave --no-restore -e 'shiny::runApp(port = 3000)' &
- R -e 'devtools::check()'
addons:
  sauce_connect:
    username: "$SAUCE_USERNAME"
    access_key: "$SAUCE_SECRET_KEY"

# Added for shinyapps.io deployment
# dist: xenial
# sudo: false
# latex: false
# 
# deploy:
#   provider: script
#   script: 
#     - R -f deploy.R
#   on:
#     branch: master