# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
r_packages:
  - covr
  - rsconnect
  - devtools
  - memoise
  - parsedate
  - plyr
  - rappdirs
  - rcmdcheck
  - rematch
  - rhub
  - rversions

r_github_packages:
  - julianstanley/gfpop-gui

after_success:
  - Rscript -e 'covr::codecov()'

# Added for shinyapps.io deployment
# dist: xenial
# sudo: false
# latex: false
# 
# deploy:
#   provider: script
#   script: 
#     - R -f deploy.R
#   on:
#     branch: master