# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

# Added for shinyapps.io deployment
dist: xenial
sudo: false
latex: false
script:
  -R -f deploy.R
  
deploy:
  provider: script
  script: deploy.R
  on:
    branch: master